# Generated by Django 5.2.7 on 2025-10-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0002_cruise_inforequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inforequest',
            name='destinations',
            field=models.ManyToManyField(related_name='destinations', to='relecloud.destination'),
        ),
    ]
