# Generated by Django 5.2.7 on 2025-10-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_remove_inforequest_destinations_cruise_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
